import Image from "next/image";
import Link from "next/link";
import { SiteHeader } from "../../components/SiteHeader";
import { siteMetadata } from "../../lib/site";
export const metadata = siteMetadata({ title: "Services", alternates: { canonical: "/services" } });
export default function ServicesPage() { return <><SiteHeader /><main id="main"><section className="page-hero"><div className="shell"><p className="eyebrow">Construction · Remodeling · Gutters</p><h1>Good work, inside and out.</h1><p className="hero-copy">Tell us what needs attention. We’ll start with your home, your priorities and a free site assessment.</p><div className="actions"><Link className="button primary" href="/contact">Discuss your project ↗</Link><a className="text-link" href="tel:+14063502113">Call 406-350-2113</a></div></div></section><section className="section"><div className="shell">
<article className="service-detail" id="gutters"><div><p className="eyebrow">Exterior care</p><h2>Seamless gutters & repair.</h2><p>New gutter work and repairs planned around your home’s roofline and drainage. Start with a look at the condition of the system and where water needs to go.</p><ul><li>Discuss new seamless gutters or existing gutter repairs.</li><li>Point out leaks, visible damage or areas of concern.</li><li>Get a site assessment and written estimate.</li></ul><Link className="text-link" href="/contact">Talk about your gutters →</Link></div><div className="detail-photo gutters"><Image src="/gutter.webp" alt="Close-up of damaged gutter joints showing an area that needs repair" fill sizes="(max-width: 760px) 100vw, 45vw" /></div></article>
<article className="service-detail" id="remodeling"><div className="detail-photo"><Image src="/project-2.png" alt="Kitchen cabinetry, tile and sink detail shown on SLK’s website" fill sizes="(max-width: 760px) 100vw, 45vw" /></div><div><p className="eyebrow">Make the home work for you</p><h2>Remodeling & historic homes.</h2><p>Thoughtful changes for spaces you use every day. SLK works with lived-in homes, including historic homes where the existing character matters.</p><ul><li>Bring photos, ideas and the details you want to keep.</li><li>Talk through function, layout and finish priorities.</li><li>Understand the scope before making the next decision.</li></ul><Link className="text-link" href="/work">Explore home details →</Link></div></article>
<article className="service-detail" id="structural"><div><p className="eyebrow">Build on a sound foundation</p><h2>Construction & structural repairs.</h2><p>Practical construction and repair work starts with understanding the property. Walk through the areas of concern with SLK and discuss what is needed.</p><Link className="text-link" href="/contact">Arrange a site assessment →</Link></div><div className="local-panel"><h3>Planning is part of the work.</h3><p>Planning, permits and inspection coordination help organize the project before work gets underway. Dust barriers and daily cleanup are part of caring for the site.</p><Link className="text-link" href="/process">See how the process works →</Link></div></article>
</div></section><section className="section dark"><div className="shell cta-strip"><div><p className="eyebrow">A clear first step</p><h2>Let’s look at your home.</h2><p className="section-intro">Free, no-obligation assessment. Written estimate.</p></div><Link className="button primary" href="/contact">Request an assessment ↗</Link></div></section></main></>; }
