import Image from "next/image";
import Link from "next/link";
import { SiteHeader } from "../components/SiteHeader";
import { GOOGLE_BUSINESS_URL, siteMetadata } from "../lib/site";
export const metadata = siteMetadata({ title: "Construction and Remodeling in Lewistown, MT" });
export default function HomePage() {
  return <><SiteHeader /><main id="main">
    <section className="hero"><div className="hero-content"><p className="eyebrow">Your home. Our kind of work.</p><h1>Better homes.<br /> Built here<br /> in Montana.</h1><p className="hero-copy">Seamless gutters, home remodeling and structural repairs. Local help for the work your home needs, from Lewistown across Fergus County.</p><div className="actions"><Link className="button primary" href="/contact">Plan your project <span aria-hidden="true">↗</span></Link><Link className="text-link" href="/work">Explore our work →</Link></div><p className="hero-assurance">Free site assessment · Written estimates</p></div><figure className="hero-photo"><Image src="/project-2.png" alt="Light kitchen cabinetry, farmhouse sink and tile detail from SLK’s website gallery" fill preload sizes="(max-width: 760px) 100vw, 56vw" /><figcaption><span>Space for everyday living.</span><Link href="/services#remodeling">Remodeling & finish work ↗</Link></figcaption></figure></section>
    <div className="service-band"><div className="shell"><span>Care for your home, inside & out</span><Link href="/services#gutters">Seamless gutters ↗</Link><Link href="/services#remodeling">Remodeling ↗</Link><Link href="/services#structural">Structural repairs ↗</Link></div></div>
    <section className="section"><div className="shell"><div className="section-header"><div><p className="eyebrow">What can we help with?</p><h2>One home.<br />Plenty of possibilities.</h2></div><p className="section-intro">A gutter that needs attention. A kitchen ready for a change. A repair that can’t wait forever. Start with the work in front of you.</p></div><div className="home-services"><Link href="/services#remodeling" className="service-feature"><div className="service-photo"><Image src="/project-1.png" alt="Kitchen layout with white cabinetry, island and wood flooring" fill sizes="(max-width: 760px) 100vw, 48vw" /></div><div className="service-feature-copy"><span className="eyebrow">Make more of the space you have</span><h3>Remodeling & historic homes <span>↗</span></h3><p>Thoughtful changes for lived-in homes, with attention to the details worth keeping.</p></div></Link><div className="service-stack"><Link href="/services#gutters"><p className="eyebrow">Protect the outside</p><h3>Seamless gutters & repair <span>↗</span></h3><p>Gutter work planned around your roofline, drainage and Montana weather.</p></Link><Link href="/services#structural"><p className="eyebrow">Take care of the essentials</p><h3>Construction & structural repairs <span>↗</span></h3><p>Discuss the condition of your home and the practical work needed to move forward.</p></Link><Link className="text-link" href="/services">Explore all services →</Link></div></div></div></section>
    <section className="section dark"><div className="shell process-preview"><div><p className="eyebrow">The way we work</p><h2>Know the plan.<br />Feel at home.</h2><p className="section-intro">Good communication belongs on the jobsite, too. SLK starts with a site assessment and a written estimate, so there is a clear next step.</p><Link className="text-link" href="/process">Walk through the process →</Link></div><ol className="process-list"><li><span className="step-number">01</span><div><h3>See the home</h3><p>Discuss what you want to change and assess the work on site.</p></div></li><li><span className="step-number">02</span><div><h3>Put the plan in writing</h3><p>Review an estimate and talk through planning, permits and inspection coordination.</p></div></li><li><span className="step-number">03</span><div><h3>Respect the space</h3><p>Dust barriers and daily cleanup help care for your home while work is underway.</p></div></li></ol></div></section>
    <section className="section"><div className="shell area-layout"><div><p className="eyebrow">From here. Working here.</p><h2>At home in<br />Central Montana.</h2><p className="section-intro">Based in Lewistown, serving homeowners across Fergus County and nearby communities.</p><Link className="text-link" href="/service-area">Find your service area →</Link></div><div className="local-panel"><p className="eyebrow">SLK Construction and Remodeling</p><address>1207 6th Ave N<br />Lewistown, Montana</address><div className="location-list"><span>Grass Range</span><span>Denton</span><span>Winifred</span><span>Roy</span><span>Stanford</span></div><a className="text-link" href={GOOGLE_BUSINESS_URL} target="_blank" rel="noreferrer">Find SLK on Google Maps ↗</a></div></div></section>
    <section className="section closing"><div className="shell cta-strip"><div><p className="eyebrow">Let’s start with your home</p><h2>What do you have in mind?</h2><p>Arrange a free, no-obligation site assessment.</p></div><div><Link className="button primary" href="/contact">Tell us about your project ↗</Link><a className="closing-phone" href="tel:+14063502113">Or call 406-350-2113</a></div></div></section>
  </main></>;
}
